name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  swift-package-tests:
    name: Swift Package Tests
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer

      - name: Run Common library tests
        working-directory: Common
        run: swift test

  xcode-tests:
    name: Xcode Tests
    runs-on: macos-latest

    strategy:
      matrix:
        destination:
          - platform=macOS
          - platform=iOS Simulator,name=iPhone 15 Pro

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer

      - name: Run tests
        run: |
          xcodebuild test \
            -project "Creature Console.xcodeproj" \
            -scheme "Creature Console" \
            -destination "${{ matrix.destination }}"
